<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-6">
        <div class="bg-white overflow-hidden sm:rounded-lg drop-shadow-md max-w-7xl mx-auto sm:px-3 lg:px-5 border-emerald-300">
       
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eros nisi, feugiat sit amet tincidunt vitae, vulputate in orci. Nullam id tellus elit. Suspendisse potenti. Phasellus tristique diam at augue maximus dignissim. Quisque non urna non ante venenatis sagittis. Pellentesque laoreet mi commodo risus lobortis euismod. Nunc gravida risus mattis vehicula hendrerit. Ut finibus placerat neque, ac facilisis elit pellentesque sit amet. Phasellus rutrum consectetur lectus id pretium.

Praesent eros enim, sodales imperdiet lacinia non, rutrum sit amet neque. Praesent rutrum imperdiet metus et imperdiet. Pellentesque lacinia mi magna, a feugiat metus pretium et. Integer pellentesque, massa in varius ultricies, neque metus semper odio, nec condimentum lacus urna ac lacus. Etiam sed molestie magna. In facilisis ligula vitae neque blandit scelerisque. Nulla est dolor, ornare at rutrum ac, viverra eu justo.

Suspendisse sit amet orci vel felis dapibus dignissim in eu mauris. Fusce ultrices sed ante nec ullamcorper. Vivamus condimentum tellus eu metus mollis ornare. Proin vehicula nisi eget libero ultricies, eu gravida ipsum pharetra. Aliquam elementum porta mi quis elementum. Integer ligula lacus, varius non dui in, ornare pharetra nisi. Nam tincidunt quam lorem, id mattis eros viverra et. Quisque posuere urna vel quam volutpat tempus. Curabitur aliquet pulvinar volutpat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis mollis, lacus non tempor convallis, lectus lacus iaculis urna, non convallis neque dolor mattis ante. Sed vel sem at lorem vehicula vestibulum ut id ante.

Ut in semper odio, quis mollis magna. In at consectetur nulla. Sed ac ultricies metus. Sed efficitur enim sed euismod facilisis. Curabitur lacus ante, tempor quis enim et, euismod sollicitudin nunc. Donec vitae leo est. Mauris sit amet orci eget odio euismod dapibus. Nunc convallis sem dignissim egestas tempor. Nullam tempus tellus risus, ac semper nisi congue quis.

Nullam tincidunt varius mauris sed viverra. Nunc efficitur, metus eu aliquam laoreet, velit felis molestie odio, ut suscipit ipsum diam quis diam. Curabitur placerat libero ac felis tincidunt, pulvinar tempus ligula maximus. Quisque sem mauris, faucibus vel vulputate in, euismod sed lacus. Donec quis imperdiet erat, ac blandit libero. Etiam sit amet laoreet leo. Sed suscipit commodo metus, et rhoncus augue vulputate et. Nulla aliquet est non sapien maximus, fringilla faucibus velit lobortis. Vivamus pharetra et tortor ut ornare. Ut pretium mi non enim aliquet, non dignissim diam sagittis. Maecenas faucibus et elit eu rutrum. Praesent nec urna at eros vulputate interdum. Maecenas laoreet, ligula eu sodales volutpat, sapien diam dapibus libero, a convallis nulla erat vulputate lacus. Etiam vulputate tincidunt mauris, et imperdiet quam sollicitudin vitae. Aenean imperdiet ante libero, non euismod sapien rutrum nec. Nam vitae pulvinar mi, nec dictum diam.

Curabitur vel pellentesque risus, a mollis neque. Aenean posuere fermentum dui, nec dapibus libero tristique eu. Etiam auctor orci ut purus efficitur sagittis. Donec sollicitudin velit ut efficitur convallis. Sed leo nisl, bibendum eu efficitur id, elementum a eros. Integer eu malesuada libero. Nunc semper id magna vel tincidunt. Nulla ullamcorper odio neque, quis tincidunt erat bibendum vel. Phasellus massa ligula, aliquet id finibus eget, tincidunt nec odio. Donec tincidunt lorem erat, at sagittis elit viverra eu. In vel lacus congue, pulvinar purus ac, dignissim mauris.

Maecenas in ultrices elit, ac eleifend ligula. Nam porttitor maximus neque, vel feugiat sapien porttitor ac. Pellentesque sollicitudin, dolor iaculis ultricies blandit, mi nibh lacinia ante, rutrum commodo leo elit in velit. Duis malesuada ac risus id vulputate. Mauris maximus, nibh sed efficitur varius, turpis tellus tempus dui, sit amet tristique sem odio ac ipsum. Nulla porttitor tellus metus, ut efficitur urna volutpat ut. Etiam convallis, augue at euismod dapibus, ipsum metus imperdiet risus, nec accumsan arcu risus nec urna. Cras fringilla lacus orci, eget tincidunt metus ornare nec. Donec tellus ligula, porta ac ultrices ut, feugiat a urna. Sed interdum eu purus quis ullamcorper. Suspendisse sit amet neque iaculis, hendrerit ipsum sed, tempor orci. Donec eu consequat leo, id pharetra arcu. Nunc at ullamcorper ipsum. Ut vehicula justo sodales urna commodo, eu rutrum dui dictum. Donec tincidunt dignissim hendrerit.

Phasellus nec hendrerit orci, vel feugiat urna. Praesent viverra et est ut condimentum. Nam non quam est. Proin vel orci malesuada erat consequat varius consequat sed nulla. Phasellus vulputate felis in dui feugiat lacinia. Sed sit amet aliquam nisl. Fusce non lacinia lectus. Vivamus ac condimentum erat. Proin eget vestibulum lacus. Etiam vel commodo ex. Duis sit amet magna et eros efficitur fermentum. Sed aliquet a nulla et imperdiet. Cras imperdiet sollicitudin pellentesque. Duis varius, est in consequat consectetur, augue massa dictum diam, id eleifend metus dui ut eros. Cras nec mattis felis. Nunc nec nisl interdum, porttitor metus eu, varius odio.

Pellentesque augue libero, tristique vitae fringilla ut, sollicitudin eu ante. In finibus enim non eros cursus, facilisis venenatis nunc auctor. Donec sed ipsum at arcu commodo porta at sit amet felis. Nunc sit amet elit ac lacus lobortis dictum at scelerisque lacus. Duis sed enim sed felis euismod convallis. Curabitur congue lacus nisi, at imperdiet tellus condimentum sit amet. Nulla facilisi. Aliquam convallis eros ipsum, eu tincidunt nisi ullamcorper non. Praesent feugiat feugiat lorem nec ornare. Pellentesque interdum suscipit enim, eu hendrerit lectus feugiat ut. Quisque gravida, lorem sed semper elementum, ante quam efficitur mauris, id imperdiet orci erat vitae orci. Vestibulum elementum dui at imperdiet auctor. Duis eget justo scelerisque, sollicitudin mauris eget, vehicula lacus. Nullam pellentesque odio vel augue scelerisque maximus ac ultrices enim. Fusce tellus ligula, accumsan non feugiat sed, faucibus at nulla. Ut id fringilla justo.

In eu ultrices dui. Phasellus imperdiet a dui quis consequat. Duis id tortor sapien. Vestibulum id tincidunt orci. Aliquam erat volutpat. Sed a lobortis arcu. Vestibulum dapibus dapibus vulputate. Phasellus lacinia a massa eu luctus. Ut feugiat ex vel eros scelerisque scelerisque. Maecenas molestie lacus ut dictum sodales. Suspendisse ac sapien ut nunc auctor tristique nec malesuada dui. Quisque ornare velit id erat tristique ultrices. Morbi eros nisi, ullamcorper et placerat id, eleifend eu leo.

        </div>
        
    </div>
</x-app-layout>
